import Head from 'next/head';
import ImageGrid from '../components/ImageGrid';
import Socials from '../components/Socials';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Dmitry Krasnov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'h-screen flex justify-center px-2 font-mono'}>
        <div
          className={
            'flex flex-col justify-center items-center w-full max-w-[1024px] mt-14'
          }
        >
          <h1 className={'text-3xl italic font-bold'}>👋 Hello there!</h1>
          <div className={'mt-5'}>
            <div className={'p-3'}>
              <h2 className={'text-xl font-bold mt-3 underline'}>
                My name is Dmitry Krasnov
              </h2>
              <p className={'mt-3'}>
                I am a software developer from San Diego, CA 🇺🇸
              </p>
              <p className={'mt-3'}>
                There are some social links, please let me know!
              </p>

              <div className="flex justify-center">
                <Socials />
              </div>
            </div>

            <p className={'mt-5'}>
              You can check{' '}
              <a
                className={'text-white bg-sky-500 hover:bg-sky-700'}
                href={'/dmitry_krasnov_cv.pdf'}
                target={'_blank'}
                rel={'noreferrer'}
              >
                my resume
              </a>{' '}
              for more details.
            </p>
          </div>

          <div className={'w-full mt-14 flex justify-center'}>
            <ImageGrid />
          </div>
        </div>
      </main>
    </div>
  );
}
