import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'h-screen flex flex-col justify-center items-center'}>
        <div
          className={
            'flex justify-center items-center bg-black text-white'
          }
        >
          <div>
            image container
            <Image alt="photo" />
          </div>

          <div>
            <h1 className="text-3xl font-bold underline">Hello</h1>
            <h2>My name is</h2>
            <p>some description text</p>
            <div>
              some useful links
              <ul>
                <li>one</li>
                <li>two</li>
                <li>three</li>
              </ul>
              <a className={'bg-sky-500 hover:bg-sky-700'} href={'/'}>
                download cv links
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
