import Head from 'next/head';
import Image from 'next/image';
import ImageGrid from '../components/ImageGrid';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Dmitry Krasnov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          'h-screen flex flex-col justify-center items-center font-mono'
        }
      >
        <div className={'flex justify-center items-center'}>
          <ImageGrid />

          <div className={'max-w-xs'}>
            <h1 className={'text-3xl'}>Hello</h1>
            <h2 className={'text-xl font-bold mt-3 underline'}>
              My name is Dmitry Krasnov
            </h2>
            <p className={'mt-3'}>
              I am a software developer from San Diego 🇺🇸
            </p>

            <p></p>

            <ul className={'mt-3'}>
              <li>one</li>
              <li>two</li>
              <li>three</li>
            </ul>

            <p>
              You can check{' '}
              <a
                className={'text-white bg-sky-500 hover:bg-sky-700'}
                href={'/dmitry_krasnov_cv.pdf'}
                target={'_blank'}
                rel={'noreferrer'}
              >
                my resume
              </a>{' '}
              for more details
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
